apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: gcr.io/shorted-dev-aba5688f/gateway
    docker:
      dockerfile: ./Dockerfile
      buildArgs: 
        CONFIG_FILE: "{{ .CONFIG_FILE }}"
  local:
    push: true